CREATE SEQUENCE IF NOT EXISTS password_reset_token_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE fees
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    unit_price  DECIMAL                                 NOT NULL,
    CONSTRAINT pk_fees PRIMARY KEY (id)
);

CREATE TABLE invoice_item
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    invoice_id        BIGINT,
    service_detail_id BIGINT,
    quantity          INTEGER                                 NOT NULL,
    total             DECIMAL                                 NOT NULL,
    CONSTRAINT pk_invoice_item PRIMARY KEY (id)
);

CREATE TABLE invoices
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    consecutive_number INTEGER                                 NOT NULL,
    expiration_date    date                                    NOT NULL,
    payment_total      DECIMAL                                 NOT NULL,
    deleted            BOOLEAN                                 NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    modified_date      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_invoices PRIMARY KEY (id)
);

CREATE TABLE issuers
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    business_name VARCHAR(50)                             NOT NULL,
    nit           VARCHAR(10)                             NOT NULL,
    address       VARCHAR(254)                            NOT NULL,
    email         VARCHAR(254)                            NOT NULL,
    phone_number  VARCHAR(15)                             NOT NULL,
    deleted       BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_issuers PRIMARY KEY (id)
);

CREATE TABLE password_reset_token
(
    id              BIGINT                      NOT NULL,
    token           VARCHAR(255)                NOT NULL,
    user_id         BIGINT                      NOT NULL,
    expiration_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_passwordresettoken PRIMARY KEY (id)
);

CREATE TABLE payments
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount             DECIMAL                                 NOT NULL,
    payment_date_time  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    invoice_id         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_payments PRIMARY KEY (id)
);

CREATE TABLE refresh_token
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token           VARCHAR(255),
    user_id         BIGINT,
    expiration_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_refresh_token PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name         VARCHAR(50)                             NOT NULL,
    last_name          VARCHAR(50)                             NOT NULL,
    document           VARCHAR(10),
    email              VARCHAR(254)                            NOT NULL,
    password           VARCHAR(255)                            NOT NULL,
    address            VARCHAR(254),
    phone_number       VARCHAR(15),
    role               VARCHAR(255),
    active             BOOLEAN                                 NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE issuers
    ADD CONSTRAINT uc_issuers_email UNIQUE (email);

ALTER TABLE issuers
    ADD CONSTRAINT uc_issuers_nit UNIQUE (nit);

ALTER TABLE password_reset_token
    ADD CONSTRAINT uc_passwordresettoken_token UNIQUE (token);

ALTER TABLE password_reset_token
    ADD CONSTRAINT uc_passwordresettoken_user UNIQUE (user_id);

ALTER TABLE refresh_token
    ADD CONSTRAINT uc_refresh_token_token UNIQUE (token);

ALTER TABLE refresh_token
    ADD CONSTRAINT uc_refresh_token_user UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_document UNIQUE (document);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE invoice_item
    ADD CONSTRAINT FK_INVOICE_ITEM_ON_INVOICE FOREIGN KEY (invoice_id) REFERENCES invoices (id);

ALTER TABLE invoice_item
    ADD CONSTRAINT FK_INVOICE_ITEM_ON_SERVICE_DETAIL FOREIGN KEY (service_detail_id) REFERENCES fees (id);

ALTER TABLE password_reset_token
    ADD CONSTRAINT FK_PASSWORDRESETTOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE payments
    ADD CONSTRAINT FK_PAYMENTS_ON_INVOICE FOREIGN KEY (invoice_id) REFERENCES invoices (id);

ALTER TABLE refresh_token
    ADD CONSTRAINT FK_REFRESH_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);