CREATE SEQUENCE IF NOT EXISTS password_reset_token_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE accounting_regimes
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50)                              NOT NULL,
    CONSTRAINT pk_accounting_regimes PRIMARY KEY (id)
);

CREATE TABLE departments
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(30)                              NOT NULL,
    CONSTRAINT pk_departments PRIMARY KEY (id)
);

CREATE TABLE economic_activities
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50)                              NOT NULL,
    CONSTRAINT pk_economic_activities PRIMARY KEY (id)
);

CREATE TABLE invoice_issuers
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    business_name          VARCHAR(50)                             NOT NULL,
    nit                    VARCHAR(10)                             NOT NULL,
    address                VARCHAR(254)                            NOT NULL,
    municipality_id        INTEGER,
    email                  VARCHAR(254)                            NOT NULL,
    phone_number           VARCHAR(15)                             NOT NULL,
    accounting_regime_id   INTEGER,
    responsibility_type_id INTEGER,
    economic_activity_id   INTEGER,
    operation_type_id      INTEGER,
    negotiation_type_id    SMALLINT,
    deleted                BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_invoice_issuers PRIMARY KEY (id)
);

CREATE TABLE invoice_item
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    invoice_id        BIGINT,
    service_detail_id BIGINT,
    quantity          INTEGER                                 NOT NULL,
    total             DECIMAL                                 NOT NULL,
    CONSTRAINT pk_invoice_item PRIMARY KEY (id)
);

CREATE TABLE invoiced_users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT,
    invoice_id BIGINT,
    status     VARCHAR(255),
    CONSTRAINT pk_invoiced_users PRIMARY KEY (id)
);

CREATE TABLE invoices
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    consecutive_number  INTEGER                                 NOT NULL,
    invoice_issuer_id   BIGINT,
    operation_type_id   INTEGER,
    negotiation_type_id SMALLINT,
    expiration_date     date                                    NOT NULL,
    payment_total       DECIMAL                                 NOT NULL,
    deleted             BOOLEAN                                 NOT NULL,
    created_date        TIMESTAMP WITHOUT TIME ZONE,
    modified_date       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_invoices PRIMARY KEY (id)
);

CREATE TABLE municipalities
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(30)                              NOT NULL,
    department_id INTEGER,
    CONSTRAINT pk_municipalities PRIMARY KEY (id)
);

CREATE TABLE negotiation_types
(
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT pk_negotiation_types PRIMARY KEY (id)
);

CREATE TABLE operation_types
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_operation_types PRIMARY KEY (id)
);

CREATE TABLE password_reset_token
(
    id              BIGINT                      NOT NULL,
    token           VARCHAR(255)                NOT NULL,
    user_id         BIGINT                      NOT NULL,
    expiration_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_passwordresettoken PRIMARY KEY (id)
);

CREATE TABLE payment_methods
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50)                              NOT NULL,
    CONSTRAINT pk_payment_methods PRIMARY KEY (id)
);

CREATE TABLE payments
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount             DECIMAL                                 NOT NULL,
    payment_date_time  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    payment_method_id  INTEGER,
    invoiced_user_id   BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_payments PRIMARY KEY (id)
);

CREATE TABLE refresh_token
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token           VARCHAR(255),
    user_id         BIGINT,
    expiration_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_refresh_token PRIMARY KEY (id)
);

CREATE TABLE responsibility_types
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50)                              NOT NULL,
    CONSTRAINT pk_responsibility_types PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_name VARCHAR(255),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE service_details
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    unit_price  DECIMAL                                 NOT NULL,
    CONSTRAINT pk_service_details PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name         VARCHAR(50)                             NOT NULL,
    last_name          VARCHAR(50)                             NOT NULL,
    document           VARCHAR(10),
    email              VARCHAR(254)                            NOT NULL,
    password           VARCHAR(255)                            NOT NULL,
    address            VARCHAR(254),
    phone_number       VARCHAR(15),
    role_id            INTEGER,
    active             BOOLEAN                                 NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE departments
    ADD CONSTRAINT uc_departments_name UNIQUE (name);

ALTER TABLE invoice_issuers
    ADD CONSTRAINT uc_invoice_issuers_email UNIQUE (email);

ALTER TABLE invoice_issuers
    ADD CONSTRAINT uc_invoice_issuers_nit UNIQUE (nit);

ALTER TABLE municipalities
    ADD CONSTRAINT uc_municipalities_name UNIQUE (name);

ALTER TABLE password_reset_token
    ADD CONSTRAINT uc_passwordresettoken_token UNIQUE (token);

ALTER TABLE password_reset_token
    ADD CONSTRAINT uc_passwordresettoken_user UNIQUE (user_id);

ALTER TABLE refresh_token
    ADD CONSTRAINT uc_refresh_token_token UNIQUE (token);

ALTER TABLE refresh_token
    ADD CONSTRAINT uc_refresh_token_user UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_document UNIQUE (document);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_role UNIQUE (role_id);

ALTER TABLE invoiced_users
    ADD CONSTRAINT FK_INVOICED_USERS_ON_INVOICE FOREIGN KEY (invoice_id) REFERENCES invoices (id);

ALTER TABLE invoiced_users
    ADD CONSTRAINT FK_INVOICED_USERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE invoices
    ADD CONSTRAINT FK_INVOICES_ON_INVOICE_ISSUER FOREIGN KEY (invoice_issuer_id) REFERENCES invoice_issuers (id);

ALTER TABLE invoices
    ADD CONSTRAINT FK_INVOICES_ON_NEGOTIATION_TYPE FOREIGN KEY (negotiation_type_id) REFERENCES negotiation_types (id);

ALTER TABLE invoices
    ADD CONSTRAINT FK_INVOICES_ON_OPERATION_TYPE FOREIGN KEY (operation_type_id) REFERENCES operation_types (id);

ALTER TABLE invoice_issuers
    ADD CONSTRAINT FK_INVOICE_ISSUERS_ON_ACCOUNTING_REGIME FOREIGN KEY (accounting_regime_id) REFERENCES accounting_regimes (id);

ALTER TABLE invoice_issuers
    ADD CONSTRAINT FK_INVOICE_ISSUERS_ON_ECONOMIC_ACTIVITY FOREIGN KEY (economic_activity_id) REFERENCES economic_activities (id);

ALTER TABLE invoice_issuers
    ADD CONSTRAINT FK_INVOICE_ISSUERS_ON_MUNICIPALITY FOREIGN KEY (municipality_id) REFERENCES municipalities (id);

ALTER TABLE invoice_issuers
    ADD CONSTRAINT FK_INVOICE_ISSUERS_ON_NEGOTIATION_TYPE FOREIGN KEY (negotiation_type_id) REFERENCES negotiation_types (id);

ALTER TABLE invoice_issuers
    ADD CONSTRAINT FK_INVOICE_ISSUERS_ON_OPERATION_TYPE FOREIGN KEY (operation_type_id) REFERENCES operation_types (id);

ALTER TABLE invoice_issuers
    ADD CONSTRAINT FK_INVOICE_ISSUERS_ON_RESPONSIBILITY_TYPE FOREIGN KEY (responsibility_type_id) REFERENCES responsibility_types (id);

ALTER TABLE invoice_item
    ADD CONSTRAINT FK_INVOICE_ITEM_ON_INVOICE FOREIGN KEY (invoice_id) REFERENCES invoices (id);

ALTER TABLE invoice_item
    ADD CONSTRAINT FK_INVOICE_ITEM_ON_SERVICE_DETAIL FOREIGN KEY (service_detail_id) REFERENCES service_details (id);

ALTER TABLE municipalities
    ADD CONSTRAINT FK_MUNICIPALITIES_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES departments (id);

ALTER TABLE password_reset_token
    ADD CONSTRAINT FK_PASSWORDRESETTOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE payments
    ADD CONSTRAINT FK_PAYMENTS_ON_INVOICED_USER FOREIGN KEY (invoiced_user_id) REFERENCES invoiced_users (id);

ALTER TABLE payments
    ADD CONSTRAINT FK_PAYMENTS_ON_PAYMENT_METHOD FOREIGN KEY (payment_method_id) REFERENCES payment_methods (id);

ALTER TABLE refresh_token
    ADD CONSTRAINT FK_REFRESH_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id);