spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://localhost:5433/acueducto_db
spring.datasource.username=postgres
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8080

jwt.access.cookie.name=accessCookie
jwt.refresh.cookie.name=refreshCookie
jwt.secret=${JWT_KEY}
jwt.accessToken.expirationMs=300000
jwt.refreshToken.expirationMs=86400000


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest


rabbitmq.users.exchange=users.exchange
rabbitmq.email.send.password.reset.queue=email.send.password.reset.queue
rabbitmq.email.send.password.reset.routing.key=email.send.password.reset.routing.key
rabbitmq.users.handle.response.password.reset.success.queue=users.handle.response.password.reset.success.queue
rabbitmq.users.handle.response.password.reset.success.routing.key=users.handle.response.password.reset.success.routing.key
rabbitmq.users.handle.response.password.reset.failed.queue=users.handle.response.password.reset.failed.queue
rabbitmq.users.handle.response.password.reset.failed.routing.key=users.handle.response.password.reset.failed.routing.key


logging.level.org.springframework.security=WARN
logging.level.org.flywaydb=DEBUG
